// <auto-generated />
namespace KaartingenGrootDeinze.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Nieuwsbericht_kaartingidweg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nieuwsbericht_kaartingidweg));
        
        string IMigrationMetadata.Id
        {
            get { return "202001251625298_Nieuwsbericht_kaartingid weg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
